develop release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -65,6 +65,34 @@ jobs:
           with:
             node-version: 20
             registry-url: https://registry.npmjs.org/
+        - name: Install pnpm
+          run: npm install -g pnpm
+    
+        - name: Detect package manager
+          id: detect-package-manager
+          run: |
+              set -x  # Enable debug mode
+              if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+                echo "manager=pnpm" >> $GITHUB_OUTPUT
+                echo "command=install" >> $GITHUB_OUTPUT
+                echo "runner=pnpm" >> $GITHUB_OUTPUT
+                exit 0
+              elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                echo "manager=yarn" >> $GITHUB_OUTPUT
+                echo "command=install" >> $GITHUB_OUTPUT
+                echo "runner=yarn" >> $GITHUB_OUTPUT
+                exit 0
+              elif [ -f "${{ github.workspace }}/package.json" ]; then
+                echo "manager=npm" >> $GITHUB_OUTPUT
+                echo "command=ci" >> $GITHUB_OUTPUT
+                echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                exit 0
+              else
+                echo "Unable to determine package manager"
+                exit 1
+              fi
+            
+      
         - run: pnpm install --no-frozen-lockfile
         - run: npm publish
           env:
